### ISSUE TITLE
Issue with json struct tag omitempty

### ISSUE THREAD

**Issue by PatrLind** [shigetaichi/xsv#20]
I found this bug in gocsv: https://github.com/gocarina/gocsv/issues/263
and thought I would test the same on your project, since it seems better in many ways.
But unfortunately it seems that this project has the same bug, or at least what I think is a bug.

The error is that the code panics when having json struct tags with omitempty on them. I haven't investigated very deeply, but it seems like it should not panic.

Example panic output:
```
--- FAIL: TestCSV (0.00s)
    --- FAIL: TestCSV/test_1_json (0.00s)
panic: reflect: call of reflect.Value.Field on zero Value [recovered]
	panic: reflect: call of reflect.Value.Field on zero Value

```

Test code I used:
```golang
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"testing"

	"github.com/shigetaichi/xsv"
)

type TestObj struct {
	Name    string     `json:"name,omitempty"`
	SubObj  *TestOb2   `json:"subObj,omitempty"`
	SubObjs []*TestOb2 `json:"subObjs,omitempty"`
}

type TestOb2 struct {
	A string `json:"a,omitempty"`
	B string `json:"b,omitempty"`
}

func TestCSV(t *testing.T) {
	obj1 := []*TestObj{
		{
			Name: "Obj1",
			SubObj: &TestOb2{
				A: "a1",
				B: "b1",
			},
			SubObjs: []*TestOb2{
				{
					A: "a2",
					B: "b2",
				},
				{
					A: "a3",
					B: "b3",
				},
			},
		},
	}

	testCases := []struct {
		TagName string
	}{
		{"json"}, {"csv"},
	}
	for i, tc := range testCases {
		tc := tc
		t.Run(fmt.Sprintf("test_%d_%s", i+1, tc.TagName), func(t *testing.T) {
			xsvWrite := xsv.NewXsvWrite[*TestObj]()
			xsvWrite.TagName = tc.TagName
			buf := bytes.NewBuffer(nil)
			err := xsvWrite.SetBufferWriter(buf).Write(obj1)
			if err != nil {
				t.Error(err)
			}
			fmt.Println("Buf:", buf.String())
			obj2 := []*TestObj{}
			xsvReader := xsv.NewXsvRead[*TestObj]()
			xsvReader.TagName = tc.TagName
			err = xsvReader.SetStringReader(buf.String()).ReadTo(&obj2)
			if err != nil {
				t.Error(err)
			}
			if fmt.Sprint(obj1) != fmt.Sprint(obj2) {
				t.Errorf("objects not equal. Obj1: %v, Obj2: %v", obj1, obj2)
			}
		})
	}
}

func (o *TestObj) String() string {
	data, err := json.Marshal(o)
	if err != nil {
		panic(err)
	}
	return string(data)
}

```

**Comment by PatrLind** [comment]
I investigated a little bit more, and found that I could change this code (https://github.com/shigetaichi/xsv/blob/main/types.go#L220) from:
```golang
		if omitEmpty && value == "" {
			return nil
		}
```
to:
```golang
		if omitEmpty && value == "" {
			field.Set(reflect.New(field.Type().Elem()))
			return nil
		}

```
and it seems to work, not sure if it breaks something...

**Comment by PatrLind** [comment]
I made a fork with a small fix that seems to work. The tests passes at least. But, I'm actually not sure if it breaks something...
https://github.com/shigetaichi/xsv/commit/7e010c2b4e24826723ba0f266cd443e99d45e86b

**Comment by shigetaichi** [comment]
@PatrLind 
Thank you for your careful description and writing. Your contribution is welcome.
I have also checked with me about this. Some of the information is unclear, but it is information sharing.

---

I am getting an error with a pointer type of primitive type with omitempty attached.
It seems like the error occurred in the opposite of the way you suggested, correctly.

To verbalize [the process that line 220](https://github.com/shigetaichi/xsv/blob/main/types.go#L220) is doing,
Reassign the underlying type of the pointer type to the 'field' variable in the case of a field of pointer type with "omitempty attached" and "empty string coming across".
is.

If the field is "structure pointer type and omitempty", then the change description you gave us will assign the specified type to the field argument, which will allow us to execute [the decode.go line 171 process](https://github.com/shigetaichi/xsv/blob/c1aafc9f27fcc7ea921be2586e05d9e53e00f351/decode.go#L171) correctly.

On the other hand, if the field is a "primitive pointer type and omitempty", **the process is still not followed properly**😅.

**Comment by shigetaichi** [comment]
https://github.com/gocarina/gocsv/issues/135
I have read the above issue. 
I am not too sure what the omitempty behavior in the gocsv package means anymore.
~I thought it was "if all the data in the field is zero, the entire column is removed from the output", but it seems that this is not the case.~
Sorry, I see that omitempty is a function that specifies whether or not a pointer type field should be set to nil when a type string is entered into it.

~If you don't need omitempty as a feature, i may want to remove it from the package.~

**Comment by shigetaichi** [comment]
@PatrLind 
The first argument of setField comes in to get the initial value of each field, plz check [```setInnerField``` func](https://github.com/shigetaichi/xsv/blob/c1aafc9f27fcc7ea921be2586e05d9e53e00f351/decode.go#L139).
If each field is a pointer type, the initial value will be nil.

At that point, it would determine if the tag had ```omitempty``` or if the value from the csv was an empty string, and if both condition was met, it would do nothing and move on to the next field.

This 👆  part was the factor of this issue.
In the case of **fields of nested pointer type structs**, ```setInnerField``` is executed recursively, so the first argument of ```setField``` may contain a struct in the middle of the nest.

Since the existing code only checked for ```omitempty``` and empty characters, the processing of the ```setField``` function was interrupted when the struct in the middle of the nest was a pointer type, and the processing was not transferred to the field of the nested struct itself.

I have created a PR and plz check here. -> https://github.com/shigetaichi/xsv/pull/21
I have also added one test.
Thank you for creating the issue and investigating the problem🙇.

**Comment by PatrLind** [comment]
Your changes in the PR seems to fix the issue, thank you!

**Comment by otodak** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
bravura-quark, @ducanh2706, @wuliaoiii, @githubth, @happilysheep, @SeanDiFusco, @tanguanyuan, @lawal-mj, @Jurshsmith, @G0o9leA1, @pcaversaccio, @Farfetchedchild, @EmperorJesus, @dr-gareth-roberts, @ezreal1997, @spinales, @dhomane, @mind1949, @zainamroti, @jun9, @iobruno, @bryansayler, @onrcn, @KaioH3, @dibaliqaja, @javaDeveloperBook, @naotwu, @SecLoop, @AlanDev99, @kawamou, @sachin-kiwi, @handlemyfinance, @fabjordan, @tri2820, @prabakarviji, @Moroshima, @sntsabode, @arjunshibu, @harshal0815, @earyantLe, @pranav280300, @WayneChang65, @linhnt31, @dvilcasanmspe, @onemedicine, @taiak, @banyudu, @isgasho, @icheernoom, @toast-gear
